name: CI


on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ main ]


jobs:
  
  build:
    
    runs-on: ubuntu-latest

   

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      - name: Compile Extension
        run: |
          npm install
          npm run start