name: CI


on:
  push:
    branches: [ beta ]
 


jobs:
  
  build:
    
    runs-on: windows-latest

   

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
            envkey_DEBUG: false
            envkey_MAPS_API_KEY : ${{secrets.MAPS_API_KEY}}
          
        

        
            
      - name: Compile Extension
        run: |
          npm install
          npm run build
          cat dist/background.js
