name: Build and Deploy to AMO

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
      
        run: |
          New-Item .env
          Set-Content .env "FIREFOX_JWT_ISSUER = ${{secrets.FIREFOX_JWT_ISSUER}}"
          Add-Content .env "FIREFOX_JWT_SECRET = ${{secrets.FIREFOX_JWT_SECRET}}"
          Add-Content .env "FIREFOX_EXTENSION_UUID = ${{secrets.FIREFOX_EXTENSION_UUID}}"
          
          
      - name: Compile Extension
        run: |
          npm install
          npm run syncVersion
          npm run build

      - name: Deploy Extension
        run: |
          npm run firefoxDeploy
          
