on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
        
      - name: Open Web Client Directory
        working-directory: src/contentScript
        run: |
          ls -la
